#!/bin/bash
# Launch development tasks from inside the development docker container

if [ -z "${UID}" ]; then
    UID="$(id -u)"
fi
export UID

if [ -z "${GID}" ]; then
    GID="$(id -g)"
fi
export GID

COMPOSE_FILE="ci/docker/docker-compose.yaml"
SERVICE_NAME="website-builder"

# Check if test:e2e is in the arguments
for arg in "$@"; do
    if [ "$arg" = "test:e2e" ]; then
        SERVICE_NAME="website-tester"
        break
    fi
done

exec docker compose --file "${COMPOSE_FILE}" run \
    --rm \
    --interactive \
    --volume "${PWD}:${PWD}:rw" \
    --workdir "${PWD}" \
    "${SERVICE_NAME}" \
    task "$@"
