---
version: "3"

includes:
  build: './ci/tasks/build'
  ci: './ci/tasks/ci'
  dev: './ci/tasks/dev'
  lint: './ci/tasks/lint'

tasks:
  default:
    desc: List available commands
    cmds:
      - '{{.TASK_EXE}} --list-all'
