---
version: "3"

vars:
  BUILDER_REQUIREMENTS: '{{.ROOT_DIR}}/ci/docker/website-builder/requirements.txt'
  VENV_DIR: '{{.ROOT_DIR}}/.venv'
  PYEXE:
    sh: |
      if which python3 >/dev/null 2>&1; then
        echo python3 && exit 0
      fi
      if which python >/dev/null 2>&1; then
        echo python && exit 0
      fi
      exit 1

tasks:
  start:
    desc: "Start development server"
    preconditions:
      - sh: which yarn >/dev/null 2>&1
        msg: Missing "yarn". Please install yarn
    deps:
      - install-packages
    cmds:
      - yarn dev
  setup-venv:
    desc: "Set up Python virtual environment"
    cmds:
      - |
        if [ ! -d "{{.VENV_DIR}}" ]; then
          "{{.PYEXE}}" -m venv "{{.VENV_DIR}}"
        fi
      - |
        . "{{.VENV_DIR}}/bin/activate"
        "{{.PYEXE}}" -m pip install -r "{{.BUILDER_REQUIREMENTS}}"
        playwright install chromium
  install-packages:
    desc: Install yarn packages
    internal: true
    preconditions:
      - sh: which yarn >/dev/null 2>&1
        msg: Missing "yarn". Please install yarn
    cmds:
      - echo "${YARN_CACHE_FOLDER}"
      - yarn install
    env:
      CI: true
    generates:
      - node_modules/**
    sources:
      - 'package.json'
      - 'yarn.lock'
