---
name: Build

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: task build:package
      - uses: actions/upload-artifact@v4
        with:
          name: 'website'
          path: './website.tar.zst'
          if-no-files-found: error
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: task test:unit
