---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  e2e-test:
    name: End to End Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    container:
      image: ${{ inputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: 'website'
      - name: Extract Build
        run: |
          archive_name="$(find . -name 'website.tar.*' -print -quit)"
          if [ -z "${archive_name}" ]; then
            echo "missing archive?" >&2
            exit 1
          fi
          echo "Found archive: ${archive_name}"

          # extract to dist so that the e2e tests can be run like this or from a dev env
          mkdir -p dist
          tar -C dist -xf "${archive_name}"
      - name: Run Tests
        # ignore the deps that are normally included
        run: task BROWSER=${{ matrix.browser }} test:e2e-ci
